/*
 Navicat Premium Dump SQL

 Source Server         : Local Postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 160003 (160003)
 Source Host           : localhost:5432
 Source Catalog        : vidly
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160003 (160003)
 File Encoding         : 65001

 Date: 25/01/2025 00:40:23
*/


-- ----------------------------
-- Sequence structure for Customers_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Customers_Id_seq";
CREATE SEQUENCE "public"."Customers_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Genres_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Genres_Id_seq";
CREATE SEQUENCE "public"."Genres_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Movies_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Movies_Id_seq";
CREATE SEQUENCE "public"."Movies_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Rentals_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Rentals_Id_seq";
CREATE SEQUENCE "public"."Rentals_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Users_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Users_Id_seq";
CREATE SEQUENCE "public"."Users_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for Customers
-- ----------------------------
DROP TABLE IF EXISTS "public"."Customers";
CREATE TABLE "public"."Customers" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "IsGold" bool NOT NULL DEFAULT false,
  "Phone" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of Customers
-- ----------------------------
INSERT INTO "public"."Customers" VALUES (1, 'Noman', 'f', '03222691789');
INSERT INTO "public"."Customers" VALUES (3, 'Noman', 't', '03222691789');
INSERT INTO "public"."Customers" VALUES (5, 'Amins', 'f', '03222819054');
INSERT INTO "public"."Customers" VALUES (6, 'string', 't', 'string');
INSERT INTO "public"."Customers" VALUES (7, 'string', 't', 'string');

-- ----------------------------
-- Table structure for Genres
-- ----------------------------
DROP TABLE IF EXISTS "public"."Genres";
CREATE TABLE "public"."Genres" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of Genres
-- ----------------------------
INSERT INTO "public"."Genres" VALUES (258, 'string2');
INSERT INTO "public"."Genres" VALUES (261, 'string7');
INSERT INTO "public"."Genres" VALUES (262, 'string8');
INSERT INTO "public"."Genres" VALUES (269, 'updated');
INSERT INTO "public"."Genres" VALUES (268, 'updated string');
INSERT INTO "public"."Genres" VALUES (257, 'updated string 2');
INSERT INTO "public"."Genres" VALUES (260, 'updated string 260');
INSERT INTO "public"."Genres" VALUES (274, 'My Genre');

-- ----------------------------
-- Table structure for Movies
-- ----------------------------
DROP TABLE IF EXISTS "public"."Movies";
CREATE TABLE "public"."Movies" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Title" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "GenreId" int4 NOT NULL DEFAULT 0,
  "NumberInStock" int4 NOT NULL,
  "DailyRentalRate" int4 NOT NULL
)
;

-- ----------------------------
-- Records of Movies
-- ----------------------------
INSERT INTO "public"."Movies" VALUES (20, 'My Movie', 261, 10, 20);
INSERT INTO "public"."Movies" VALUES (21, 'My Movie 3', 261, 10, 20);
INSERT INTO "public"."Movies" VALUES (23, 'My Movie 5', 261, 10, 20);

-- ----------------------------
-- Table structure for Rentals
-- ----------------------------
DROP TABLE IF EXISTS "public"."Rentals";
CREATE TABLE "public"."Rentals" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "CustomerId" int4 NOT NULL DEFAULT 0,
  "MovieId" int4 NOT NULL DEFAULT 0,
  "DateOut" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DateReturned" timestamptz(6),
  "RentalFee" int4 NOT NULL
)
;

-- ----------------------------
-- Records of Rentals
-- ----------------------------
INSERT INTO "public"."Rentals" VALUES (20, 3, 23, '2024-09-03 22:26:12+05', '2024-09-16 22:26:34.186642+05', 260);
INSERT INTO "public"."Rentals" VALUES (21, 5, 23, '2025-01-03 19:16:26.652023+05', '2025-01-22 19:18:46.992628+05', 380);

-- ----------------------------
-- Table structure for Users
-- ----------------------------
DROP TABLE IF EXISTS "public"."Users";
CREATE TABLE "public"."Users" (
  "Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "Email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "Password" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL,
  "IsAdmin" bool NOT NULL
)
;

-- ----------------------------
-- Records of Users
-- ----------------------------
INSERT INTO "public"."Users" VALUES (20, 'noman', 'noman@gmail.com', '$2a$10$crc90EOiRnfopLLDZDGfOusTkXESzhuGtgrct4TEGgT.Cy.ZSFRRK', 'f');
INSERT INTO "public"."Users" VALUES (22, 'amin shoukat', 'amin@gmail.com', '$2a$10$oVhAb.CY4V/58s8nmYVrvOjmAc27EexvKMcEy85WyeGM8Me4yfO3K', 't');
INSERT INTO "public"."Users" VALUES (21, 'noman', 'nomanaadma@gmail.com', '$2a$10$TwlbnJDyRJjTr6Nzg98RN.I/tZUbL6pWSIN.NJXwyK7eie5Op2TRK', 't');

-- ----------------------------
-- Table structure for __EFMigrationsHistory
-- ----------------------------
DROP TABLE IF EXISTS "public"."__EFMigrationsHistory";
CREATE TABLE "public"."__EFMigrationsHistory" (
  "MigrationId" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "ProductVersion" varchar(32) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of __EFMigrationsHistory
-- ----------------------------
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20240911175838_init', '8.0.8');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20240912070835_fkeyRequired_datetimeFix', '8.0.8');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20240916123004_makeRentalReturnOptional', '8.0.8');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Customers_Id_seq"
OWNED BY "public"."Customers"."Id";
SELECT setval('"public"."Customers_Id_seq"', 7, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Genres_Id_seq"
OWNED BY "public"."Genres"."Id";
SELECT setval('"public"."Genres_Id_seq"', 274, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Movies_Id_seq"
OWNED BY "public"."Movies"."Id";
SELECT setval('"public"."Movies_Id_seq"', 23, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Rentals_Id_seq"
OWNED BY "public"."Rentals"."Id";
SELECT setval('"public"."Rentals_Id_seq"', 21, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Users_Id_seq"
OWNED BY "public"."Users"."Id";
SELECT setval('"public"."Users_Id_seq"', 22, true);

-- ----------------------------
-- Auto increment value for Customers
-- ----------------------------
SELECT setval('"public"."Customers_Id_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table Customers
-- ----------------------------
ALTER TABLE "public"."Customers" ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for Genres
-- ----------------------------
SELECT setval('"public"."Genres_Id_seq"', 274, true);

-- ----------------------------
-- Primary Key structure for table Genres
-- ----------------------------
ALTER TABLE "public"."Genres" ADD CONSTRAINT "PK_Genres" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for Movies
-- ----------------------------
SELECT setval('"public"."Movies_Id_seq"', 23, true);

-- ----------------------------
-- Indexes structure for table Movies
-- ----------------------------
CREATE INDEX "IX_Movies_GenreId" ON "public"."Movies" USING btree (
  "GenreId" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Movies
-- ----------------------------
ALTER TABLE "public"."Movies" ADD CONSTRAINT "PK_Movies" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for Rentals
-- ----------------------------
SELECT setval('"public"."Rentals_Id_seq"', 21, true);

-- ----------------------------
-- Indexes structure for table Rentals
-- ----------------------------
CREATE INDEX "IX_Rentals_CustomerId" ON "public"."Rentals" USING btree (
  "CustomerId" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "IX_Rentals_MovieId" ON "public"."Rentals" USING btree (
  "MovieId" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table Rentals
-- ----------------------------
ALTER TABLE "public"."Rentals" ADD CONSTRAINT "PK_Rentals" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for Users
-- ----------------------------
SELECT setval('"public"."Users_Id_seq"', 22, true);

-- ----------------------------
-- Primary Key structure for table Users
-- ----------------------------
ALTER TABLE "public"."Users" ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table __EFMigrationsHistory
-- ----------------------------
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");

-- ----------------------------
-- Foreign Keys structure for table Movies
-- ----------------------------
ALTER TABLE "public"."Movies" ADD CONSTRAINT "FK_Movies_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES "public"."Genres" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Rentals
-- ----------------------------
ALTER TABLE "public"."Rentals" ADD CONSTRAINT "FK_Rentals_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "public"."Customers" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."Rentals" ADD CONSTRAINT "FK_Rentals_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "public"."Movies" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
